// <auto-generated />
namespace NGT.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class BDComplement10 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BDComplement10));
        
        string IMigrationMetadata.Id
        {
            get { return "202212040028027_BDComplement-10"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
